import { useState } from 'react';
import { Eye, Brain, MessageSquare, Cpu, Layers, Zap, ChevronRight } from 'lucide-react';

const projectCards = [
  {
    id: 'cv',
    icon: Eye,
    title: 'Computer Vision',
    subtitle: 'Object Detection with YOLOv8',
    description: 'Advanced object detection using YOLOv8 model trained on COCO dataset to identify and locate objects in images with precise bounding boxes.',
    technologies: ['Python', 'OpenCV', 'Ultralytics YOLO', 'NumPy'],
    details: [
      'Real-time object detection',
      'Bounding box visualization',
      'Confidence scoring',
      'CPU-optimized inference'
    ],
    color: 'primary'
  },
  {
    id: 'nlp',
    icon: Brain,
    title: 'NLP Understanding',
    subtitle: 'Scene Analysis with BERT',
    description: 'Semantic scene understanding using BERT to classify environments, extract context, and analyze crowd dynamics from detected objects.',
    technologies: ['PyTorch', 'HuggingFace', 'Transformers', 'Tokenizers'],
    details: [
      'Scene type classification',
      'Context extraction',
      'Crowd analysis',
      'Lightweight processing'
    ],
    color: 'info'
  },
  {
    id: 'llm',
    icon: MessageSquare,
    title: 'AI Explanation',
    subtitle: 'Reasoning with LLaMA',
    description: 'Natural language explanations generated by LLaMA 3.2 that transform structured data into human-readable scene descriptions.',
    technologies: ['LLaMA 3.2', 'ctransformers', 'Prompt Engineering'],
    details: [
      'Natural language output',
      'Context-aware explanations',
      'Instruction-based prompting',
      'CPU-compatible models'
    ],
    color: 'success'
  },
  {
    id: 'architecture',
    icon: Layers,
    title: 'System Architecture',
    subtitle: 'Modular & Scalable Design',
    description: 'Clean separation of concerns with independent modules for perception, understanding, and reasoning that can be developed and scaled individually.',
    technologies: ['FastAPI', 'React', 'MongoDB', 'Render'],
    details: [
      'Microservices architecture',
      'Independent scaling',
      'Modular development',
      'Production-ready deployment'
    ],
    color: 'warning'
  }
];

export const ProjectOverviewSection = () => {
  return (
    <section className="py-24 bg-gradient-to-b from-card/30 to-background">
      <div className="container mx-auto px-4">
        <div className="text-center mb-16">
          <h2 className="text-3xl sm:text-4xl font-bold mb-4">
            <span className="text-foreground">Deep Dive Into Our </span>
            <span className="gradient-text">AI System</span>
          </h2>
          <p className="text-muted-foreground max-w-2xl mx-auto text-lg">
            Explore the cutting-edge technologies powering our multimodal visual scene understanding platform
          </p>
        </div>

        <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-6">
          {projectCards.map((card) => {
            const Icon = card.icon;
            return (
              <div
                key={card.id}
                className="group relative p-6 rounded-2xl bg-card border border-border/50 transition-all duration-500 hover:shadow-xl hover:border-primary/30"
                style={{
                  animationDelay: `${Math.random() * 0.3}s`
                }}
              >
                {/* Icon */}
                <div className="w-12 h-12 rounded-xl bg-primary/10 flex items-center justify-center mb-4 group-hover:scale-110 transition-transform duration-300">
                  <Icon className="w-6 h-6 text-primary" />
                </div>

                {/* Content */}
                <h3 className="text-xl font-semibold text-foreground mb-2">
                  {card.title}
                </h3>
                <p className="text-sm text-primary font-medium uppercase tracking-wider mb-3">
                  {card.subtitle}
                </p>
                <p className="text-muted-foreground mb-4 text-sm leading-relaxed">
                  {card.description}
                </p>

                {/* Technologies */}
                <div className="flex flex-wrap gap-2 mb-4">
                  {card.technologies.map((tech) => (
                    <span
                      key={tech}
                      className="px-2 py-1 text-xs rounded-full bg-secondary text-muted-foreground"
                    >
                      {tech}
                    </span>
                  ))}
                </div>

                {/* Details */}
                <div className="pt-4 border-t border-border/50">
                  <ul className="space-y-2">
                    {card.details.map((detail, index) => (
                      <li key={index} className="flex items-start gap-2 text-sm text-muted-foreground">
                        <ChevronRight className="w-4 h-4 text-primary flex-shrink-0 mt-0.5" />
                        <span>{detail}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              </div>
            );
          })}
        </div>

        {/* Stats Section */}
        <div className="mt-16 grid grid-cols-2 md:grid-cols-4 gap-6">
          {[
            { label: 'AI Models', value: '3', icon: Cpu },
            { label: 'Processing Stages', value: '4', icon: Layers },
            { label: 'Technologies', value: '15+', icon: Zap },
            { label: 'Accuracy Rate', value: '92%', icon: Brain },
          ].map((stat, index) => {
            const Icon = stat.icon;
            return (
              <div 
                key={stat.label}
                className="p-6 rounded-2xl bg-card border border-border/50 text-center hover:border-primary/30 transition-colors"
                style={{ animationDelay: `${0.1 + index * 0.05}s` }}
              >
                <div className="w-12 h-12 rounded-xl bg-primary/10 flex items-center justify-center mx-auto mb-4">
                  <Icon className="w-6 h-6 text-primary" />
                </div>
                <div className="text-2xl font-bold text-foreground mb-1">{stat.value}</div>
                <div className="text-sm text-muted-foreground">{stat.label}</div>
              </div>
            );
          })}
        </div>
      </div>
    </section>
  );
};