import { useState } from 'react';
import { MessageSquare, Copy, Check, RefreshCw, AlertTriangle, Info } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { cn } from '@/lib/utils';

interface ExplanationPanelProps {
  explanation: string;
  onRegenerate: () => void;
  isRegenerating: boolean;
}

export const ExplanationPanel = ({
  explanation,
  onRegenerate,
  isRegenerating,
}: ExplanationPanelProps) => {
  const [copied, setCopied] = useState(false);

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(explanation);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error('Failed to copy:', err);
    }
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between flex-wrap gap-4">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-xl bg-success/10 flex items-center justify-center">
            <MessageSquare className="w-5 h-5 text-success" />
          </div>
          <div>
            <h3 className="font-semibold text-foreground">AI Explanation</h3>
            <p className="text-sm text-muted-foreground">Natural language scene description</p>
          </div>
        </div>

        <div className="flex items-center gap-2">
          <Button
            variant="ghost"
            size="sm"
            onClick={handleCopy}
            disabled={isRegenerating}
          >
            {copied ? (
              <>
                <Check className="w-4 h-4 text-success" />
                <span>Copied</span>
              </>
            ) : (
              <>
                <Copy className="w-4 h-4" />
                <span>Copy</span>
              </>
            )}
          </Button>
          <Button
            variant="outline"
            size="sm"
            onClick={onRegenerate}
            disabled={isRegenerating}
          >
            <RefreshCw className={cn("w-4 h-4", isRegenerating && "animate-spin")} />
            <span>Regenerate</span>
          </Button>
        </div>
      </div>

      {/* Explanation Content */}
      <div className="relative p-6 rounded-2xl bg-gradient-to-br from-success/5 to-transparent border border-success/20">
        {isRegenerating && (
          <div className="absolute inset-0 bg-background/80 backdrop-blur-sm rounded-2xl flex items-center justify-center z-10">
            <div className="flex flex-col items-center gap-3">
              <div className="flex gap-1">
                <div className="processing-dot" />
                <div className="processing-dot" />
                <div className="processing-dot" />
              </div>
              <p className="text-sm text-muted-foreground">Regenerating explanation...</p>
            </div>
          </div>
        )}

        <p className="text-foreground leading-relaxed whitespace-pre-wrap text-lg">
          {explanation}
        </p>

        {/* AI Model Badge */}
        <div className="mt-6 pt-4 border-t border-border/50 flex items-center justify-between flex-wrap gap-3">
          <div className="flex items-center gap-2">
            <span className="text-xs text-muted-foreground">Generated by</span>
            <span className="px-2.5 py-1 rounded-full bg-success/10 text-success text-xs font-semibold">
              LLaMA 3.2
            </span>
          </div>
          <div className="flex items-center gap-1.5 text-xs text-muted-foreground">
            <Info className="w-3 h-3" />
            <span>Grounded in detected objects</span>
          </div>
        </div>
      </div>

      {/* AI Disclaimer */}
      <div className="flex items-start gap-3 p-4 rounded-xl bg-warning/5 border border-warning/20">
        <AlertTriangle className="w-5 h-5 text-warning shrink-0 mt-0.5" />
        <div className="text-sm">
          <p className="text-foreground font-medium mb-1">AI-Generated Content</p>
          <p className="text-muted-foreground leading-relaxed">
            This explanation is generated based on detected objects and learned scene understanding. 
            While grounded in visual analysis, interpretations may vary. The AI aims to describe 
            what is objectively visible without hallucination.
          </p>
        </div>
      </div>
    </div>
  );
};
